costmap_filter_info_server:
  ros__parameters:
    use_sim_time: true
    type: 0
    filter_info_topic: "costmap_filter_info"
    mask_topic: "map_mask"
    base: 0.0
    multiplier: 1.0
map_mask_server:
  ros__parameters:
    use_sim_time: true
    frame_id: "map"
    topic_name: "map_mask"
    yaml_filename: "keepout_mask.yaml"
